naturalheritage_search_homepage:
    path:     /
    defaults: { _controller: NaturalheritageSearchBundle:Default:index }

naturalheritage_search_homepage_iframe:
    path:     /iframe
    defaults: { _controller: NaturalheritageSearchBundle:Default:indexiframe }


naturalheritage_search_searchelasticsearch:
    path:     /search/{textpattern}
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:searchelasticsearch 

naturalheritage_search_searchelasticsearchpartial:
    path:     /searchpartial
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:searchelasticsearchforpartial 
        page: 1

naturalheritage_search_autocompleteelasticsearch:
    path:     /autocomplete/{textpattern}
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocomplete
        textpattern: "" 

naturalheritage_search_autocompletefulltext:
    path:     /autocompletefulltext
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocompletefulltext


naturalheritage_field_autocompleteselectall:
    path:     /autocompletegetall/{keywordfield}
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocompletefieldall

naturalheritage_search_autocompletewho:
    path:     /autocompletewho
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocompletewho

naturalheritage_search_autocompletewhere:
    path:     /autocompletewhere
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocompletewhere            

naturalheritage_search_autocompletewhat:
    path:     /autocompletewhat
    defaults:  
        _controller: NaturalheritageSearchBundle:Default:autocompletewhat            
                
